server:
  port: 0

spring:
  application:
    name: NOTIFICATION-SERVICE

  config:
    import: optional:configserver:http://localhost:8094

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notificationId
      properties:
        spring:
          json:
            type:
              mapping: event:com.notificationservice.StudentPlacedEvent