server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**

        - id: SUBJECT-SERVICE
          uri: lb://SUBJECT-SERVICE
          predicates:
            - Path=/subject/**

  config:
    import: optional:configserver:http://localhost:8094

#  zipkin:
#    base-url: http://127.0.0.1:9411/
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka